### ISSUE TITLE
linking to DOCX standard scientific style

### ISSUE THREAD

**Issue by sballesteros** [scienceai/scholarly.vernacular.io#22]
As an example of why scholarly HTML is useful as a target spec. DOCX standard scientific style was designed so that DOCX can be "easily" automatically converted to scholarly HTML.

**Comment by darobin** [comment]
I would do this right now, but DS3 is still private. Can we open it? Does it need some love to be put on the internets? Maybe just as a `gh-pages`? + @tiffbogich

**Comment by sballesteros** [comment]
yeah @tiffbogich is working on it will be a gh-pages.

**Comment by darobin** [comment]
Ok, I've mentioned the relationship with a link to http://scienceai.github.io/docx-standard-scientific-style (no pressure ;-)
