### ISSUE TITLE
Don't define which HTML elements are supported, just note which are meaningful 

### ISSUE THREAD

**Issue by ptsefton** [scienceai/scholarly.vernacular.io#41]
HTML5 is already well defined - it is not necessary to list all the elements people may choose to use - just the ones that have a specific meaning in Scholarly HTML

**Comment by darobin** [comment]
That depends on the context. Outside of the parts meant to be consumed by an SH processor, sure, we should prescribe nothing (and we don't).

Where SH content is concerned however, if we want useful interoperability we need some constraints over arbitrary HTML. SH is only really valuable if it can be tooled properly. If we define it to basically be arbitrary HTML with a bit of semantic sugar on top then the only tooling that can do anything much with it is an arbitrary HTML editor for production and an arbitrary HTML parser for consumption. Neither of those are very appealing (to me) propositions. They basically reflect the status quo (just embed some schema.org in HTML and you're done, that's already done all over the place).

Scholarly production is much more than just dumping linear text in a container. Many steps do (or could) interact from authoring to automated checking to data integration to typesetting, indexing, etc. Using arbitrary HTML makes it little more than a standard fig leaf over the same archaic situation that prevails with Word or LaTeX. Building a solid, open ecosystem of supporting tooling around scholarly production requires more meaningful, more processable content; not just in the metadata but in the full structure of the provided information.
