### ISSUE TITLE
Meta viewport

### ISSUE THREAD

**Issue by darobin** [scienceai/scholarly.vernacular.io#6]
In the page and required in spec.

**Comment by frivoal** [comment]
Any opposition in principle to @viewport[1], or just being pragmatic with what's broadly supported?

[1] https://drafts.csswg.org/css-device-adapt/

**Comment by darobin** [comment]
Completely the latter. Making it a format requirement sort of forces people to actually make use of this feature (so many scholarly publishers today seem to rely on server-side detection to send different content...), but that's not a huge deal.

**Comment by frivoal** [comment]
Makes sense. Do you see any migration path to @viewport in 2 years or 20, when more browsers get around supporting it? Or should we just make a normative section on how to interpret the meta viewport in terms of @viewport, and leave authors alone?

**Comment by frivoal** [comment]
(I mean in the @viewport spec, not in the scholarly html spec)

**Comment by darobin** [comment]
TBH I haven't looked at the `@viewport` spec in a little while. So long as it adds some features and some sanity, there's a transition path to it. I expect it to be a slow one, but I'm sure people would gradually switch it from their HTML templates to their CSS templates (likely with both at the same time for a very substantial period). We're talking closer to a decade, 2 years is unrealistic.

**Comment by frivoal** [comment]
Yes, I agree.
